[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = [
  "curl -sS https://bootstrap.pypa.io/get-pip.py -o get-pip.py",
  "python get-pip.py --break-system-packages",
  "python -m venv /opt/venv",
  "/opt/venv/bin/pip install --upgrade pip setuptools wheel",
  "/opt/venv/bin/pip install -r requirements.txt"
]

[start]
cmd = "uvicorn app.main:app --host 0.0.0.0 --port $PORT"

