[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = [
  "curl -sS https://bootstrap.pypa.io/get-pip.py -o get-pip.py",
  "python get-pip.py --break-system-packages",
  "python -m venv /opt/venv",
  "/opt/venv/bin/pip install --upgrade pip setuptools wheel",
  "/opt/venv/bin/pip install -r requirements.txt"
]

[start]
cmd = "python -m gunicorn app.main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT"

